<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\eDhaq.Models\eDhaq.Models.csproj" />
    <ProjectReference Include="..\eDhaq.Common\eDhaq.Common.csproj" />
    <ProjectReference Include="..\eDhaq.Data\eDhaq.Data.csproj" />
    <ProjectReference Include="..\eDhaq.Repositories\eDhaq.Repositories.csproj" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.104.2" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="9.0.6" />
    <PackageReference Include="QuestPDF" Version="2025.7.0" />
    <PackageReference Include="QRCoder" Version="1.6.0" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
