<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\eDhaq.Models\eDhaq.Models.csproj" />
    <ProjectReference Include="..\eDhaq.Common\eDhaq.Common.csproj" />
    <ProjectReference Include="..\eDhaq.Data\eDhaq.Data.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
